#ifndef ANIMATIONS_H
#define ANIMATIONS_H

enum Animation
{
    
    PLAYER_STAND,
    PLAYER_RUN,
    PLAYER_JUMP_UP,
    PLAYER_JUMP_DOWN,
    PLAYER_FALL_UP,
    PLAYER_FALL_DOWN,
    PLAYER_FALL_RIGHT,
    PLAYER_FALL_LEFT,
    PLAYER_SWORD,
    PLAYER_SWORD_FALL,
    PLAYER_BOW,
    PLAYER_BOW_FINISH,
    PLAYER_KNOCKBACK,
    PLAYER_KNOCKBACK_FALL,
    
    ODIN_STAND,
    ODIN_RUN,
    ODIN_FALL,
    ODIN_SPEER_WAIT,
    ODIN_SPEER_WAIT_FALL,
    ODIN_SPEER_THROW,
    ODIN_SPEER_THROW_FALL,
    ODIN_HIT_WAIT,
    ODIN_HIT,
    ODIN_LIGHTNING_WAIT,
    ODIN_LIGHTNING_THROW,
    ODIN_KNOCKBACK,
    ODIN_KNOCKBACK_EXPLOSION
};

#endif